# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-17 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rec_book_number', models.CharField(max_length=128)),
                ('is_teacher', models.BooleanField()),
                ('telegram_id', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseUser',
        ),
    ]
