# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_list',
            field=models.ManyToManyField(to='courses.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher_id', to='courses.User'),
        ),
    ]
