# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181219_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='users_list',
            new_name='users',
        ),
    ]
